export const DESKTOP_DISTRIBUTION_IDENTITY = {
  appId: "com.samuelsaid.t3code",
  baseName: "T3 Code (Samuel)",
  packageName: "t3code-samuel",
  productName: "T3 Code (Samuel)",
  nightlyProductName: "T3 Code (Samuel Nightly)",
  developmentDisplayName: "T3 Code (Samuel Dev)",
  artifactPrefix: "T3-Code-Samuel",
  productionScheme: "t3code-samuel",
  developmentScheme: "t3code-samuel-dev",
  updateRepository: "samuelsaid2003/t3code",
  desktopHomeDirName: ".t3-samuel",
  productionUserDataDirName: "t3code-samuel",
  developmentUserDataDirName: "t3code-samuel-dev",
  productionLegacyUserDataDirName: "T3 Code (Samuel)",
  developmentLegacyUserDataDirName: "T3 Code (Samuel Dev)",
  productionLinuxId: "t3code-samuel",
  developmentLinuxId: "t3code-samuel-dev",
} as const;
